### ISSUE TITLE
Error when using custom paper size

### ISSUE THREAD

**Issue by PaulWieland** [martip/node-red-contrib-html-to-pdf#4]
When I try and use the "Custom" paper size, the node reports an error: `"Error: Unknown paper format: custom"`

**Comment by PaulWieland** [comment]
There are two and a half issues:

1. The custom paper size units are [not being set](https://github.com/martip/node-red-contrib-html-to-pdf/blob/7a005ac33cb9fbc30475c0729d19fe528902ce1d/html-to-pdf/html-to-pdf.js#L30) in `this.options`. The units are also not being saved in the node (value is lost after deploy).
2. 'custom' is not a valid paper format, but it is being set in `this.options`. [This line](https://github.com/martip/node-red-contrib-html-to-pdf/blob/7a005ac33cb9fbc30475c0729d19fe528902ce1d/html-to-pdf/html-to-pdf.js#L28) should be removed and use `if(config.format === "custom")` instead.

**Comment by martip** [comment]
Merged @PaulWieland PR

**Comment by martip** [comment]
Published version 1.0.2 on **npm** and **Node-RED**.
